# Generated by Django 2.1 on 2018-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityLAL',
            fields=[
                ('city', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('enrollment_year', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WechatMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='none', max_length=20)),
                ('teacher_id', models.CharField(default='none', max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('city_count', models.IntegerField()),
                ('province', models.CharField(default='none', max_length=20)),
                ('country', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WechatSex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='none', max_length=20)),
                ('teacher_id', models.CharField(default='none', max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('sex_male', models.IntegerField()),
                ('sex_female', models.IntegerField()),
                ('sex_other', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WechatWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='none', max_length=20)),
                ('teacher_id', models.CharField(default='none', max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('word', models.CharField(max_length=20)),
                ('word_count', models.IntegerField()),
            ],
        ),
    ]
