# Generated by Django 2.1 on 2018-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='sex',
            field=models.CharField(default='男', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='sex',
            field=models.CharField(default='男', max_length=2),
            preserve_default=False,
        ),
    ]
