# Generated by Django 2.1 on 2018-12-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20181203_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wechatmap',
            old_name='student_id',
            new_name='type_id',
        ),
        migrations.RenameField(
            model_name='wechatsex',
            old_name='student_id',
            new_name='type_id',
        ),
        migrations.RenameField(
            model_name='wechatword',
            old_name='student_id',
            new_name='type_id',
        ),
        migrations.RemoveField(
            model_name='wechatmap',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='wechatsex',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='wechatword',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='date',
            field=models.CharField(default='nome', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='date',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatmap',
            name='type',
            field=models.CharField(default='none', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatsex',
            name='type',
            field=models.CharField(default='none', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatword',
            name='type',
            field=models.CharField(default='none', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wechatsex',
            name='sex_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wechatsex',
            name='sex_male',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wechatsex',
            name='sex_other',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citylal',
            name='country',
            field=models.CharField(default='中国', max_length=20),
        ),
        migrations.AddField(
            model_name='citylal',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citylal',
            name='province',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citylal',
            name='city',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
